apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  creationTimestamp: null
  name: "9041189982890951637"
  namespace: default
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/emailallau/testnewflux
status: {}
