apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  creationTimestamp: null
  name: kcust9041189982890951637
  namespace: default
spec:
  interval: 5m0s
  path: clusters/provider1flux+cluster2/context/9041189982890951637
  prune: true
  sourceRef:
    kind: GitRepository
    name: "9041189982890951637"
  targetNamespace: default
status: {}
